name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Setup chromedriver
      uses: nanasess/setup-chromedriver@master
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run robot tests
      run: bash run_robot_tests.sh
    - name: Coverage test
      run: coverage run --branch -m pytest
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
        AZURE_POSTGRESQL_CONNECTIONSTRING: 'host=localhost:5432 dbname=testdb user=testuser password=testpassword'
    - name: Coverage report
      run: coverage xml
    - name: Coverage report to Codecov
      run: bash <(curl -s https://codecov.io/bash)
    - name: Pylint app
      run: pylint app
    - name: Pylint tests
      run: pylint tests
